### ISSUE TITLE
3013004 lost classtype field

### ISSUE THREAD

**Issue by lrvy** [al0ne/suricata-rules#4]
This rule don't have classtype field.

alert tcp $HOME_NET any -> any any (msg: "http GET data"; flow: established;  content:"|47 45 54|"; depth: 10; content:"|0d 0a 0d 0a|"; depth:500; pcre:"/\x0d\x0a\x0d\x0a[^GETPOSTPUTHEAD\{\<\-][\x00-\xff]{100,200}/"; sid: 3013004; rev: 1; metadata:created_at 2018_10_17,by al0ne;)

**Comment by al0ne** [comment]
1/8/2019 -- 23:23:03 - <Info> - Running suricata under test mode
1/8/2019 -- 23:23:03 - <Notice> - This is Suricata version 4.1.0 RELEASE
1/8/2019 -- 23:23:03 - <Info> - CPUs/cores online: 2
1/8/2019 -- 23:23:03 - <Info> - eve-log output device (regular) initialized: eve.json
1/8/2019 -- 23:23:03 - <Info> - stats output device (regular) initialized: stats.log
1/8/2019 -- 23:23:04 - <Info> - 2 rule files processed. 10679 rules successfully loaded, 0 rules failed
1/8/2019 -- 23:23:04 - <Info> - Threshold config parsed: 0 rule(s) found
1/8/2019 -- 23:23:04 - <Info> - 10680 signatures processed. 0 are IP-only rules, 3832 are inspecting packet payload, 8437 inspect application layer, 0 are decoder event only
1/8/2019 -- 23:23:07 - <Notice> - Configuration provided was successfully loaded. Exiting.


我刚刚试了试 我写的所有规则在4.1.0版本可以 看来后期的版本应该有变动

**Comment by lrvy** [comment]
> 1/8/2019 -- 23:23:03 - - Running suricata under test mode
> 1/8/2019 -- 23:23:03 - - This is Suricata version 4.1.0 RELEASE
> 1/8/2019 -- 23:23:03 - - CPUs/cores online: 2
> 1/8/2019 -- 23:23:03 - - eve-log output device (regular) initialized: eve.json
> 1/8/2019 -- 23:23:03 - - stats output device (regular) initialized: stats.log
> 1/8/2019 -- 23:23:04 - - 2 rule files processed. 10679 rules successfully loaded, 0 rules failed
> 1/8/2019 -- 23:23:04 - - Threshold config parsed: 0 rule(s) found
> 1/8/2019 -- 23:23:04 - - 10680 signatures processed. 0 are IP-only rules, 3832 are inspecting packet payload, 8437 inspect application layer, 0 are decoder event only
> 1/8/2019 -- 23:23:07 - - Configuration provided was successfully loaded. Exiting.
> 
> 我刚刚试了试 我写的所有规则在4.1.0版本可以 看来后期的版本应该有变动

回的是另一条Issue吧，这条没问题，就是缺少classtype字段，
