### ISSUE TITLE
False positive? 3016006

### ISSUE THREAD

**Issue by alternativesurfer** [al0ne/suricata-rules#7]
I am receiving an alert on: 3016006 from an iPhone on my network.
Is this a false positive?

10/30/2019-09:05:10.232851  [**] [1:3016006:1] Weevely PHP Backdoor Response [**] [Classification: Executable Code was Detected] [Priority: 1] {TCP} 70.186.27.16:80 -> 192.XXX.XXX.XXX:40060

**Comment by al0ne** [comment]
Please write down the complete request body and response body
