### ISSUE TITLE
请问下有没有一个优秀的 suricata 推荐的 yaml 配置文件部署。

### ISSUE THREAD

**Issue by xx-zhang** [al0ne/suricata-rules#8]
- 当前不知道什么环境下使用哪些规则
- 不知道redis存还是到文件->elk
- suricata 优化，部署在 docker(host) 和 宿主机的差别。
> 当然我都可以测试，但是没有系统的说明，差别到底多大，影响的因素有哪些

**Comment by al0ne** [comment]
参考下我的这个文档 https://github.com/al0ne/suricata_optimize
